home/urls.py
from django.urls import path

from . import views

app_name = 'home'

urlpatterns = [
    path('', views.index, name='index'),
    path('detail/<str:doc_id>/', views.detail, name="detail")
]

my_app/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path("admin/", admin.site.urls),
    path('', include('home.urls'))
]

home/models.py
from django.db import models

# Create your models here.

home/views.py
from django.shortcuts import render
import sys
import os
from .myModel import eval_whole
from datetime import datetime

# Create your views here.

def index(request):
    query = request.GET.get('search_box')

    start_time = datetime.now()
    totalTime=None
    
    if query == None or query == "":
        context = {
            'query': query,
            'flag': -1
        }
        return render(request, 'home/index.html', context)
    else:
        result = {}
        sys.path.append(os.path.join(os.path.dirname(__file__)))
        result_raw = eval_whole(100, query)
        flag = 0

        if result_raw != None:       
            for (doc_id, _) in result_raw:
                col = int(doc_id)//100 + 1
                text_file = os.path.dirname(__file__) + "/collection/" + str(col) + "/" + str(doc_id) +".txt"
                text = open(text_file).read()
                text = text.lower()
                result[doc_id] = text
            flag = 1

        end_time = datetime.now()
        totalTime = end_time-start_time

        context = {
            'result': result,
            'query': query,
            'flag': flag,
            'totalTime' : totalTime,
            'lenResult' : len(result)
        }
        
        return render(request, 'home/index.html', context)

def detail(request, doc_id):
    n = int(doc_id)//100 + 1
    dir_text = os.path.dirname(__file__) + "/collection/" + str(n) + "/" + str(doc_id) +".txt"
    text = open(dir_text).read()

    context = {
        'doc_id': doc_id,
        'text': text,
    }
   
    return render(request, 'home/detail.html', context)

home/templates/home/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">    
  <link rel="stylesheet" href="{% static 'css/style.css' %}">
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
  {% block meta %}
  {% endblock meta %}
</head>

<body style="height:100vh;margin:0;padding:0;background-color:#cfcfc4;">
  
</body>
{% block content %}
{% endblock content %}  

  
</html>

home/templates/home/detail.html
{% extends 'home/base.html' %}

{% block meta %}
    <title>{{ doc_id }}</title>
{% endblock meta %}

{% block content %}
    <div class="home" >
        <h1 class="display-4">{{ doc_id }}.txt</h1>
        <p>{{ text }}</p>
    </div>
</body>
{% endblock content %}

home/templates/home/index.html
{% extends 'home/base.html' %}

{% block meta %}
    <title>Medical Search</title>
{% endblock meta %}

{% block content %}

    <div class="home">

        <form action="{% url 'home:index' %}" method="get">
            <div class="mb-3">
                <h1 class="text-center">Medical Search</h1>
                <input type="text" placeholder="Search Your Query" class="form-control" id="search_box" name="search_box", value="{{ query|default_if_none:'' }}">
            </div>
            <div class="mb-3">
                <button type="submit" class="btn btn-primary">Search</button>
            </div>
        </form>

        {% if flag == -1 %} 
        {% else %} 
            {% if flag == 0 %}        
                <p>Result: {{ lenResult }} doc(s),  total time: {{ totalTime }}</p>
                <h3 class="text-center">Sorry, there is no result. Please try another query.</h3>
            {% else %}  
                <p>Result: {{ lenResult }} doc(s),  total time: {{ totalTime }}</p>
                <hr>
                {% for doc_id, text in result.items %}
                    <a href="{% url 'home:detail' doc_id %}">{{ doc_id }}.txt</a>
                    <br>
                    {{ text|truncatechars:150 }}
                    <br>
                    <hr>
                {% endfor %}
            {% endif %}
        {% endif %}

    </div>
{% endblock content %}